runtime: nodejs
vm: true
api_version: 1
threadsafe: true
inbound_services:
- warmup
resources:
  cpu: 0.5
  memory_gb: 0.15
  disk_size_gb: 10
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cool_down_period_sec: 120 # default value
  cpu_utilization:
    target_utilization: 0.5
handlers:
- url: /.*
  script: IGNORED
  secure: never
